version: '{build}'

branches:
  only:
  - main

skip_branch_with_pr: true
max_jobs: 1

image: Visual Studio 2019

environment:
  nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build
